CREATE TABLE `DYNAMIC_DATA_SOURCE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_SOURCE_KEY` varchar(255) NOT NULL,
  `DB_DRIVER` varchar(255) NOT NULL,
  `DB_USER` varchar(255) NOT NULL,
  `DB_PASSWORD` varchar(255) NOT NULL,
  `DB_URL` varchar(255) NOT NULL,
  `DATA_SOURCE_MIN_POOL_SIZE` varchar(255) NOT NULL,
  `DATA_SOURCE_MAX_POOL_SIZE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
);